server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=PayrollDB;encrypt=false;trustServerCertificate=true
    username: sa
    password: 245689731
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      max-lifetime: 1200000
      register-mbeans: true
      connection-init-sql: USE PayrollDB
  profiles:
    active: dev
  
  jpa:
    hibernate:
      ddl-auto: none  # 改为 none，防止自动修改表结构
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          lob:
            non_contextual_creation: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xuhao.salary.infrastructure.persistence.entity
  # 移除 mapper-locations 配置，因为我们使用注解方式

security:
  jwt:
    secret-key: ${JWT_SECRET:your-default-secret-key-must-be-at-least-256-bits-long}
    token-validity: ${JWT_TOKEN_VALIDITY:86400000}
    refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:604800000}
    issuer: salary-management-system
    expiration: ${JWT_TOKEN_VALIDITY:86400000}
    refresh-token:
      expiration: ${JWT_REFRESH_TOKEN_VALIDITY:604800000}

application:
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true
    max-age: 3600

logging:
  level:
    '[com.xuhao.salary]': debug
    '[org.mybatis]': debug
