server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=PayrollDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: 245689731
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    packages-to-scan: com.xuhao.salary.domain.model

  redis:
    host: localhost
    port: 6379
    
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xuhao.salary.domain.model

jwt:
  secret: your_jwt_secret_key_here
  expiration: 86400

# 跨域配置
cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Content-Type,Authorization
  allow-credentials: true
