server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=salary_db;encrypt=false;trustServerCertificate=true;integratedSecurity=false
    username: sa
    password: 245689731
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        '[format_sql]': true
        '[globally_quoted_identifiers]': true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

logging:
  level:
    '[com.xuhao.salary]': debug
    '[org.mybatis]': debug
